spring:
  profiles:
    active: live
  session:
    store-type: redis
  redis:
    host: 192.168.25.46
    port: 6379

zuul:
  ignoredServices: "*"
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
  routes:
    javaServiceTreeFrameworkBackendServer-DWR:
      path: /dwr/**
      url: http://192.168.25.46:31313/dwr
      sensitiveHeaders: Cookie,Set-Cookie
    javaServiceTreeFrameworkBackendServer-AuthAnon:
      path: /auth-anon/**
      url: http://192.168.25.46:31313/auth-anon
      sensitiveHeaders: Cookie,Set-Cookie
    javaServiceTreeFrameworkBackendServer-AuthUser:
      path: /auth-user/**
      url: http://192.168.25.46:31313/auth-user
      sensitiveHeaders: Cookie,Set-Cookie
    javaServiceTreeFrameworkBackendServer-AuthAdmin:
      path: /auth-admin/**
      url: http://192.168.25.46:31313/auth-admin
      sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  eureka:
    enabled: false